In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("./aeroclasses.csv")

In [4]:
dataset.head()

class   main_axis   max_defect   min_defect   area_ratio
0      0       5.000        18700          343   224.736842
1      0     110.018         9193          114     0.355248
2      0     117.290        10810          114     0.354821
3      0       3.162        15819        15819   277.857143
4      0       5.099        27019        27019   222.240000

In [5]:
X = dataset.drop('class', axis=1)
y = dataset['class']

In [6]:
from sklearn.model_selection import train_test_split

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

## SVM with linear function

In [7]:
from sklearn.svm import SVC

# Train Support vector machine
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [8]:
y_pred = svclassifier.predict(X_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[17  1  4  1  0  0]
 [ 0 19  0  0  0  1]
 [ 0  2 17  0  0  0]
 [ 0  1  0 16  0  0]
 [ 0  0  0  0 17  0]
 [ 3  1  3  0  0 17]]
              precision    recall  f1-score   support

           0       0.85      0.74      0.79        23
           1       0.79      0.95      0.86        20
           2       0.71      0.89      0.79        19
           3       0.94      0.94      0.94        17
           4       1.00      1.00      1.00        17
           5       0.94      0.71      0.81        24

   micro avg       0.86      0.86      0.86       120
   macro avg       0.87      0.87      0.87       120
weighted avg       0.87      0.86      0.86       120



## SVM with polynomial function

In [ ]:
# Train Support vector machine
svclassifier = SVC(gamma='auto', kernel='poly', degree=3)
svclassifier.fit(X_train, y_train)

In [ ]:
y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

## SVM with gaussian function

In [22]:
svclassifier = SVC(gamma='auto',kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 0  0  0 23  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0 19  0  0]
 [ 0  0  0 17  0  0]
 [ 0  0  0 15  2  0]
 [ 0  1  0 23  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        23
           1       0.00      0.00      0.00        20
           2       0.00      0.00      0.00        19
           3       0.15      1.00      0.25        17
           4       1.00      0.12      0.21        17
           5       0.00      0.00      0.00        24

   micro avg       0.16      0.16      0.16       120
   macro avg       0.19      0.19      0.08       120
weighted avg       0.16      0.16      0.07       120



/home/breno/anaconda2/envs/tf_training/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Random Forest

In [12]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=50, random_state=42)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [13]:
from sklearn import metrics

y_pred = y_pred.round().tolist()

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  3  1  0  0  0]
 [ 0 19  0  1  0  0]
 [ 0  0 15  3  1  0]
 [ 0  0  0 17  0  0]
 [ 0  0  0  0 17  0]
 [ 0  1  2  1  5 15]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.90        23
           1       0.83      0.95      0.88        20
           2       0.83      0.79      0.81        19
           3       0.77      1.00      0.87        17
           4       0.74      1.00      0.85        17
           5       1.00      0.62      0.77        24

   micro avg       0.85      0.85      0.85       120
   macro avg       0.86      0.87      0.85       120
weighted avg       0.88      0.85      0.85       120

