In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
dataset = pd.read_csv("./areaRatioData.csv")

In [23]:
dataset.head()

Class   AreaAirplane   AreaConvexHull
0      0           5.38            16.70
1      0           7.66            23.37
2      0           5.37            16.96
3      0           6.65            20.47
4      0           6.44            19.58

In [24]:
X = dataset.drop('Class', axis=1)
y = dataset['Class']

In [25]:
from sklearn.model_selection import train_test_split

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

## SVM with linear function

In [26]:
from sklearn.svm import SVC

# Train Support vector machine
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [27]:
y_pred = svclassifier.predict(X_test)

In [28]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[13  3  0  1  0  9]
 [ 2 13  1  2  2  1]
 [ 1  0  2  0  3 17]
 [ 9 10  4  1  3  0]
 [ 2  0  7  2 11  0]
 [ 5  1  1  2  3 13]]
              precision    recall  f1-score   support

           0       0.41      0.50      0.45        26
           1       0.48      0.62      0.54        21
           2       0.13      0.09      0.11        23
           3       0.12      0.04      0.06        27
           4       0.50      0.50      0.50        22
           5       0.33      0.52      0.40        25

   micro avg       0.37      0.37      0.37       144
   macro avg       0.33      0.38      0.34       144
weighted avg       0.32      0.37      0.33       144



## SVM with polynomial function

In [10]:
# Train Support vector machine
svclassifier = SVC(gamma='auto', kernel='poly', degree=3)
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [11]:
y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[18  0  0  5  0  1]
 [ 5 14  0  3  1  1]
 [ 0  0 14  1  1  7]
 [ 1  4  1  8  2  1]
 [ 1  1  3  1 25  0]
 [ 0  0  2  4  7 12]]
              precision    recall  f1-score   support

           0       0.72      0.75      0.73        24
           1       0.74      0.58      0.65        24
           2       0.70      0.61      0.65        23
           3       0.36      0.47      0.41        17
           4       0.69      0.81      0.75        31
           5       0.55      0.48      0.51        25

   micro avg       0.63      0.63      0.63       144
   macro avg       0.63      0.62      0.62       144
weighted avg       0.64      0.63      0.63       144



## SVM with gaussian function

In [67]:
svclassifier = SVC(gamma='auto',kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [68]:
y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[22  1  2  1  0  0]
 [ 4  4  3  8  1  1]
 [ 0  0 10  0  2 11]
 [ 2  4  3 10  7  1]
 [ 1  1  3  0 17  0]
 [ 1  1  9  3  6  5]]
              precision    recall  f1-score   support

           0       0.73      0.85      0.79        26
           1       0.36      0.19      0.25        21
           2       0.33      0.43      0.38        23
           3       0.45      0.37      0.41        27
           4       0.52      0.77      0.62        22
           5       0.28      0.20      0.23        25

   micro avg       0.47      0.47      0.47       144
   macro avg       0.45      0.47      0.45       144
weighted avg       0.45      0.47      0.45       144



## Random Forest

In [112]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=50, random_state=42)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [113]:
from sklearn import metrics

y_pred = y_pred.round().tolist()

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[15  7  2  2  0  0]
 [ 0  9 10  2  0  0]
 [ 0  0  7  9  7  0]
 [ 0  2  4 14  7  0]
 [ 0  0  2  1 17  2]
 [ 0  1  4  7 10  3]]
              precision    recall  f1-score   support

           0       1.00      0.58      0.73        26
           1       0.47      0.43      0.45        21
           2       0.24      0.30      0.27        23
           3       0.40      0.52      0.45        27
           4       0.41      0.77      0.54        22
           5       0.60      0.12      0.20        25

   micro avg       0.45      0.45      0.45       144
   macro avg       0.52      0.45      0.44       144
weighted avg       0.53      0.45      0.44       144

